### ISSUE TITLE
[Client] Feature / YesNoModal 구현

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#11]
### Detail
- Com/YesNoModal
  - 레이아웃
    - x 클릭 + 바깥영역 클릭시 close
    - advanced / ESC close
- 기능구현
    - props에 따라 문구 바뀜
    - 네, 아니오에 대한 처리 함수 구현

* 부모 컴포넌트는 YesNoModal로 props를 보낼 때 네, 아니오에 대한 함수 처리 과정을 묶어서 보내줘야함
- 네 - `handleAcceptAction={함수}`
- 아니오 - `handleRejectAction={함수}` 이때, 닫기 `close` 는 안 보내줘도 됨

### TODO
- [x] 기본 레이아웃
- [x] 부모 props에 따라 문구 바뀜 - props로 `comment={문구}`
- [x] 이벤트핸들러 - 바깥영역 클릭 (창 닫힘)
- [x] 이벤트핸들러 - ESC (창 닫힘)
- [x] 네, 아니오에 대한 처리 함수 구현
