### ISSUE TITLE
[Client] Feature / Plantimeline - Plancard 데이터 처리

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#111]
### Detail
* 저장하기 클릭시 서버에 보낼 데이터
* planlist 에 있는 plancard 들을 배열 형태로 데이터화
```
[
  {
    day:0,
    startTime: "10:00",
    endTime: "10:45",
    comment: "분위기 있는 카페",
    theme: 2,
    coordinates: [10, 10],
    address: "서울시 강서구 ..."
  }, ...
]
```

### TODO
- [x] PlanTimeline ->  hooks로 수정
- [x] lodash(_) library -> 순수 js로 대체
- [x] Planpage 데이터 -> Planlist에 전달해서 세팅하기
  - [x] Planpage - path에서 planId 가져오기
    - [x] PlanList에 props로 넘겨주기 
  - [x] PlanList - plancard get요청
    - [x] Redux에 세팅
  - [x] PlanTimeline 에 state 세팅
    - [x] Redux에서 가져오기
  - [x] 데이터 -> 일정으로 변경
    - 시간(string) -> height, y 좌표로 변환
- [x] layout 변경반영
- [x] plancard 변경반영
    - height, y좌표 -> 시간(string) 변환
- [x] 저장클릭시 - 변경사항 반영된 plan 보내기
  - PlanList(부모) 버튼 클릭시 -> PlanTimeline(자식) 함수 실행
  - state, 함수 내려줘야함
  - PlanTimeline에서 dispatch
- [x] 저장 클릭시 -  API 요청 
  - [x] PlanList(부모)의 다른 정보들 함께 담아서 요청
  - PlanList 함수로 요청
  - isMember === false -> 로그인창
  - isMember === true
    - path가 0 -> create
    - path가 !0 
      - isValid === true -> update
      - isValid === false -> create

### 추가할 사항들
* PlanTimeline - tsx로 변경
* setTime, setTheme값 전달, 변경 반영
* plancard 길이에 따라 -> setTime값 변화
* setTime값 변화 -> plancard값 변화
* 저장시 시간순 정렬 추가
* 삭제기능
