### ISSUE TITLE
[Client] Fix / Admin - Management 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#116]
### Detail
Management 수정

### TODO
- [x] 수정시 -> 주소입력 불가능하게 막기
- [x] 주소 세팅시 input에 입력되고, search 상태 false로 바꾸기
- [x] 승인 클릭시 -> management로 정보 넘겨주기
  - [x] management에서 승인처리 해줘야함
  - [x] 요청 아이디도 넘겨주기
