### ISSUE TITLE
[Client] Feature / MyPage 큐레이션 요청 여부 페이지 구현

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#13]
### Detail
* MyPage 큐레이션 요청여부 페이지 구현
* ListItem -> Component화 시킴 (더보기 버튼 관련 state를 관리하기 더 편하다고 생각해서)
  * CurationRequestItem.tsx
 
### TODO
- [x] 레이아웃
- [x] scss 적용
- [x] 기능 - API 요청
  - [x] get all curation request (렌더링)
  - [x] update curation request status (취소)
- [x] 기능 - 응답 데이터 Redux에 저장
- [x] 기능 - 응답 데이터 rendering 
- [x] 기능 -더보기 눌렀을 때, 세부정보 나타내주기
