### ISSUE TITLE
[Client] Fix / Planlist - representAddr input추가, 주소창 오류 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#130]
### Detail
* Planlist - representAddr input추가
* mypage, feedpage 검색창 addr 오류 수정

### TODO
- [x] 레이아웃 추가하기
- [x] scss 적용
- [x] 관련 요청에 input값 추가
- [x] 시군구 순서대로 하나씩 보여지게 하기
- [x] 상위주소 재선택시 -> 하위주소 초기화
  - 시 입력시 - 군/구 초기화
  - 군 입력시 - 구 초기화 
- [x] undefined 오류 수정
- [x] mypage 동일오류 수정
- [x] feedpage 동일오류 수정
