### ISSUE TITLE
[Client] Feature / Curation Card -> Plan Card

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#131]
### Detail
 Curation Card + 버튼 클릭시 -> Plan Card 추가되도록 구현

### TODO
- [x] planCard에 추가
  - [x] Redux 상태 변경
  - [x] 바로 렌더링되도록 useEffect 추가  
- [x] startTime 세팅
  - 현재있는 리스트 중 endTime 최댓값으로
    - [x] reduce로 max값 구하기
- [x] endTime 세팅
  - [x] startTime + 걸리는 시간

### 추가해야할 사항
* day구현 후, day값도 반영시키기
