### ISSUE TITLE
[Client] Feature / AddPlan -> PlanCard

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#133]
### Detail
 Add Plan 추가 버튼 클릭시 -> Plan Card 추가되도록 구현
* resolved #133 

### TODO
- [x] planCard에 추가
  - [x] Redux 상태 변경
- [x] startTime 세팅
  - 현재있는 리스트 중 endTime 최댓값으로
    - [x] reduce로 max값 구하기
- [x] endTime 세팅
  - [x] startTime + 걸리는 시간
