### ISSUE TITLE
[Client] Test / Curation, Curation-card API 서버 연결 테스트

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#139]
### Detail
* cuartion, curation-card API 서버 연결 테스트
* 오류 수정 
* Admin 권한문제 -> 일단 주석처리하고 진행

### TODO
**curation**
- [x] POST (admin)
  - [ ] Sever - 초기 themeInfo null일 경우 -> 수정 필요
- [x] DELETE (admin)
- [x] GET (admin, plan)
  - bearer -> Bearer (API 문서 수정필요)
  - 좌표값 encoding 추가

**curation-card**
- [x] POST (admin)
- [x] PATCH (admin)
- [x] DELETE (admin)
- [x] GET (admin, plan)
  - [x] 마커 클릭시 curationList가 뜨도록 수정 (state 올림)

### 추가할 사항
- 클라이언트에서 email 확인후 adminpage에 접근 불가능하도록 처리 
- management 좀 더 사용하기 편하게
- 이미 있는 마커인경우 알려주기
- photo값 S3버킷생성후 수정
- **google-sign** redirect 문제 #10
