### ISSUE TITLE
[Client] Fix / planlist css수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#143]
### Detail
저장버튼 위치 변경
planlist 사이즈 조절

### TODO
- [x] 저장버튼 위치 변경
- [x] planlist 사이즈 조절 
- [x] planlist box-shadow 값 변경
