### ISSUE TITLE
[Client] Feature / PlanPage 레이아웃 및 키워드 검색& 지도 이동 구현

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#15]
### Detail
* PlanPage 레이아웃
* kakaomap API 이용한 map 세팅

### TODO
- [x] 레이아웃
- [x] map 세팅
- [x] options scss 적용
- [x] theme 토글 구현 (hover시에만 뜨고 선택 가능하도록)
- [x] 내일정만 보기(눈 버튼), 큐레이션 신청 (+버튼) hover시 아래 설명 뜨도록 
- [x] 지역 키워드 검색 - kakao API 통해 좌표 받아오기
- [x] 지역 키워드 검색 - 좌표 위치로 map 이동시키기
- [x] .env에 kakao API Key 추가
