### ISSUE TITLE
[Client] Bug / Planlist, PlanTimeline 데이터 처리 및 저장 오류

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#150]
### Detail
day가 하루일때는 새로고침, 저장 시 문제가 없었는데 2일 이상일 때 문제 발생

### TODO
- [x] day가 하루일때는 새로고침, 저장 시 문제가 없었는데 2일 이상일 때 문제 발생
- [x] layout state 초기값 오류
- [x] 내일정보기 오류
- [x] AddPlan -> PlanCard 시, 추가되는 카드 시작 시간이 전체 day중 가장 늦은 시간으로 세팅되는 문제
------
- [ ] day에 일정이 없을 때 저장하면 undefined 뜸
  - day 저장시 currentDay는 올라가는데, 다시 렌더링될때 filter에서 일정이 빈 경우는 새로운 배열이 생기지 않음 
- [ ] currentDay -> Redux로 올리는게 좋을듯
