### ISSUE TITLE
[Client] Feature / MainPage - next버튼 이벤트, 맨위로 버튼 구현

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#157]
### Detail
* next 버튼에 click 이벤트 등록
*  맨위로 버튼 구현

### TODO
- [x] useRef 이용해 ref 생성 
- [x] next 버튼에 click 이벤트 등록
- [x] 맨위로 버튼 구현
  - [x] 기능
  - [x] css

* 스크롤에 따라서 페이지 자동으로 넘어가도록 구현
  * Observer 오류 해결하기
