### ISSUE TITLE
[Client] Test / Curation Request, Feedback API 서버 연결 테스트

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#161]
### Detail
Curation Request, Feedback API 서버 연결 테스트

### TODO
Curation Request
- [x] GET
- [x] POST
- [x] PATCH
  - status [x] 1 [x] 2 [x] 3 [x] 4

Curation-Feedback
- [x] GET
  - [x] 바로 렌더링 반영안되는 문제
    - POST 이후에도 GET 요청 보내도록 수정
- [x] POST
  - [x] 시간 반영안되는 오류 (setTime에서 넘겨주는값) 
  - [x] 테마 반영안되는 오류 (setTheme에서 넘겨주는값)
