### ISSUE TITLE
[Client] Test / Plan, PlanCard API 서버 테스트 - GET, POST, DELETE

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#162]
### Detail
Plan, PlanCard API 서버 연결 테스트

### TODO
Plan
- [x] GET / all
- [x] POST
  - [x] CurationCard - coordinates, address 값 오류
  - [x] AddPlan - coordinates, address 값 오류
- [x] DELETE
  - [x] 응답후 다시 GET 요청하도록 추가

Plan-Card
- [x] GET
