### ISSUE TITLE
[Client] Fix / Layout, setTime 저장관련 오류 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#164]
### Detail
state 3개로 줄임
* Redux (planCards)
* PlanList (filterByDay)
  * 실시간 변화 반영은 filterByDay가 담당
  * 나머지는 얘 영향받아 알아서 바뀜
* PlanTimeline (layoutState)

### TODO
수정
- [x] State 구조 변경

기타 오류
- [ ] 초기 시작시간 00:00 으로 세팅되는 오류
- [x] day 넘어갈때 setCurrentDay 안되는 오류
