### ISSUE TITLE
[Client] Fix / ViewCuration 이벤트 및 주소기본값, Planpage 멘트 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#182]
### Detail
Planpage 
- 전체보기 / 내꺼만보기 멘트 수정

ViewCuration 
- ESC 말고 x버튼으로도 닫히도록 
  - 뒤에 map이랑 event 겹치는 문제
- SetTime
  - 피드백 input이랑 position 겹쳐서 밀림

### TODO
- [x] SetTime position 수정 
- [x] address 기본값 수정
- [x] 전체보기 / 내꺼만보기 멘트 수정
- [x] ESC 말고 x버튼으로도 닫히도록 수정
