### ISSUE TITLE
[Client] PlanList / PlanCard - 24시 넘는경우 제한, 기타 오류 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#195]
### Detail
- PlanCard - 24시 넘게 추가하는 경우 제한, 알림
  - 추가 안되도록 처리
  - 경고알림 추가

### TODO
- [x] AddPlan
  - [x] 추가 제한
  - [x] 경고 알림 (Modal)
- [x] CurationToPlan
  - [x] 추가 제한
  - [x] 경고 알림 (Modal)
- [x] layout - max Height 속성 추가

----------
기타 오류
- [x] avgTime = 0 일때 default 1시간으로 처리
- [x] CurationList 처음에 안뜨도록
- [x] AddPlan 정상 처리후 닫히도록
