### ISSUE TITLE
[Client] Bug / 주소 입력창 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#200]
### Detail
주소창
- 하나 입력하면 하나 닫히도록
  - toggle 방식 -> hover 방식으로 변경
- 길이 길면 두줄로 처리됨 -> 넓이

### TODO
- [x] MyPage - 검색창
  - [x] 하나 입력하면 하나 닫히도록
- [x] FeedPage - 검색창
  - [x] 하나 입력하면 하나 닫히도록
- [x] PlanPage - PlanList
  - [x] 하나 입력하면 하나 닫히도록
  - [x] 길이 길면 두줄로 처리됨 -> 넓이
