### ISSUE TITLE
[Client] Bug / Curation Request 더보기, 상태변경

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#205]
### Detail
- Curation Request 더보기
- 상태에따라 취소불가 / 가능 바뀌게

### TODO
- [x] 더보기 토글 작동오류 수정
- [x] 상태에따라 취소불가 / 가능 바뀌도록 수정 
  - 0 일때만 취소 가능
- [x] 취소버튼 클릭후, 결과알림 추가
