### ISSUE TITLE
[Client] Bug / Admin Management - 검색 지도 이동

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#229]
### Detail
Admin Management - 검색 지도 이동
등록되는 좌표값 확인

### TODO
- [x] 요청에서 넘어갈시 -> 좌표값도 넘어가도록 수정
- [x] 검색시 지도 이동
- [x] 검색시 마커로 표시
