### ISSUE TITLE
[Client] Fix / Modal 개편

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#36]
### Detail
yesnoModal 좀 더 다양하게 사용 가능하도록 개편
* 인자로 모달 타입 입력받을 수 있게

### TODO
- [x] alert modal (예, 아니요 버튼 X)
- [x] input modal (input 창 & 예 - 함수실행)
- [x] 이미 사용하고 있는 부분 parameter 수정
- [x] 컴포넌트 이름 변경 (YesNoModal -> Modal)
