### ISSUE TITLE
[Client] Feature /   PlanPage 마커 / 관련 state, 함수 구현

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#38]
### Detail
  - 마커 찍을수 있게 (kakao API) 
  - 오버레이 활용

### TODO
- [x] drag controller - 마우스 드래그시 LatLng state값 변화
- [x] zoom controller - 확대/축소시 mapLevel state값 변화 
- [x] bound controller - map 이동시 bound state값 변화
- [x] 데이터(fakedata)에 따라 마커가 위치해있도록 구현
- [x] 요청받은 데이터 -> kakao lat, lng 형식에 맞게 변환하는 함수
```
// 변환 전
[
    {
      id: 0,
      coordinates: [33.450701, 126.570667],
      address: "제주도 카카오",
    },
  ]

// 변환 후 
 [{
      title: "제주도 카카오",
      latlng: new window.kakao.maps.LatLng(33.450705, 126.570677),
    },...
]
``` 
- [x] 이동시 해당 부분에 새로운 마커 렌더링
- [x] 테마별로 다른 마커 뜰 수 있게
- [x] 테마별 마커 이미지 만들기
- [x] 마커에 이벤트함수 등록 (handleClickMarker)
  - #37 애니메이션 이 함수에 등록하면됨!
