### ISSUE TITLE
[Client] Fix / MyPage scss 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#39]
### Detail
* scss 수정
* PlanSummary key props 추가

### TODO
- [x] Scss - detail 왼쪽 마진 수정
- [x] PlanSummary - key props 추가
- [x] contents 영역 margin-bottom 추가
