### ISSUE TITLE
[Client] Fix / 시군구 데이터 및 검색필터링UI, 함수 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#41]
### Detail
군 & 구 데이터 합치는 방향으로 수정

### TODO
- [x] mapdata.json 수정 (군&구 합쳐서 3depth로)
- [x] MyPage 검색 필터링 UI 수정
  - input & datalist 조합 -> a & ul/li 조합 
  - input으로 하는 경우 width를 text사이즈에 따라 조절하기 어렵다는 문제가 있었음
- [x] MyPage 검색 필터링 함수 수정
- [x] MyPage 검색 필터링 click 이벤트 함수 수정
