### ISSUE TITLE
[Client] Feature / Redux Setting

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#5]
### Detail
Redux 폴더, 파일 Setting 

### TODO
- [x] actions, reducers, store 파일 생성
- [x] 프로젝트에 필요한 initial state 구상, type 지정
```
export const initialState: State = {
  // User
  user: {
    token: "",
    email: "",
    nickname: "guest",
  },
  googleToken: "",
  // Plan
  plans: {},
  planCards: {},
  // Curation
  curations: {},
  curationCards: {},
  curationRequests: {},
};

```
- [x] actions/index.tsx - Action, Action Creators 정의
- [x] reducers
  - [x] index.tsx - Redux Persist 적용 및 combinedReducer
  - [x] initialState.tsx - 초기 state 선언
  - [x] user, plan, curation 로 reducer 구분
- [x] stores/store.tsx
  - [x] tsx에서 리덕스 디버깅 extension 사용시, window 타입을 가지지 않아 생기는 문제 해결
- [x] Index.tsx - Provider로 store 전달
- [x] useDispatch, useSelector 테스트
