### ISSUE TITLE
[Client] Fix / 지도 키워드 검색 - DataList로 변경

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#55]
### Detail
* Planpage 지도 키워드 검색 수정
* 키워드검색으로 받아온 배열 -> datalist로 구현

### TODO
- [x] 키워드 검색 요청함수, useEffect 수정
- [x] 응답으로 list 받아서 상태에 저장
- [x] ul, li 형태로 띄워주기
- [x] li 클릭이벤트로 검색하는 함수 구현
- [x] li overflow text -> ...으로 뜨도록 처리
- [x] 요청 옵션 수정 - 거리순으로 데이터 받아오도록 

* 키보드 입력시마다 요청이가서 요청 횟수가 굉장히 많아짐 - 요청횟수 줄일방법 생각해보기
