### ISSUE TITLE
[Client] Feature / NavBar 생성

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#6]
### Detail
  - 로고 : 홈 이동
  - 로그인, 회원가입 : 해당 페이지
### TODO
- [x] 레이아웃
- [x] scss 적용
- [x] public / images / logo.png 추가
- [x] 상태관리 : 로그인 상태에 따라 다른 메세지 / 함수작동
- [x] Signin, Signup 모달 실행여부 관련 state 정의
- [x] Signout API 요청함수 작성 

* Signin, Signup 모달 완성이후, 모달 띄우는함수 추가 필요 (주석처리)
