### ISSUE TITLE
[Client] Feature / CurationCard 구현, CurationList 정렬 toggle 추가

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#63]
### Detail
Props에 따라 정보 보여주기

### TODO
- [x] 레이아웃
- [x] scss
- [x] CurationList에서 props 전달 (fake데이터로 처리)
- [x] 전달받은 Props에 따라 정보 보여주기
- [x] CurationList - 최신순/시간순 정렬 toggle 추가

* CurationList width 조정
