### ISSUE TITLE
[Client] Feature / PlanList 공개&비공개 toggle 구현, 대표지역선택 추가, scss 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#67]
### Detail
* 공개&비공개 toggle 구현

### TODO
- [x] title 부분 SCSS 수정
- [x] toggle 구현
  - [x] 토글 state 추가
  - [x] scss 추가
- [x] 제목:focus 스타일 추가
- [x] 지역선택 컴포넌트화
