### ISSUE TITLE
[Client] Feature / ViewCuration 페이지 구현

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#68]
### Detail
ViewCuration 페이지 구현 

### TODO
- [x] 모달형태 레이아웃
  - 기존 react-router-dom 라우팅 제거 
- [x] 내부 레이아웃
- [x] scss 세부적용
  - [x] feedback flex - height 다른거 반영하도록
- [x] API 요청 함수 - 피드백 리스트 받기
- [x] feedback에 props 전달
- [x] 이미지 소스 추가
