### ISSUE TITLE
[Client] Feature / 일반 회원가입

### ISSUE THREAD

**Issue by JewonYeon** [codestates/scraplan-client#7]
### Detail
Component / Signup
일반 회원 가입

### TODO
- [x] 기본 레이아웃
- [x] 모달 형식으로 구현
- [x] SCSS 적용
- [x] 함수 - API 요청
- [x] 유효성 검사 - 입력여부 판단
  - [x] 입력하지 않은 부분에 따라 다른 경고메세지 (state)
  - [x] 입력하지 않은 부분으로 focus 이동하도록 구현
- [x] 이벤트핸들러 - 엔터 (다음칸으로 이동)
- [x] 이벤트핸들러 - ESC (창 닫힘)
- [x] 이벤트핸들러 - 바깥영역 클릭 (창 닫힘)
- [x] Navbar와 연결

* 소셜로그인 구현후, API 요청 이벤트 추가 필요
* E-mail인증 구현 후, API 요청 이벤트 추가 필요
* 닉네임 중복시 처리 미 구현
