### ISSUE TITLE
[Client] Feature / AddPlan 컴포넌트 구현 + Planpage 검색바 결과 수정

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#70]
## Detail
* 상태(plan 추가 / curation 요청)에 따라 다르게 구현

## TODO
- [x] 레이아웃
- [x] SCSS
- [x] setTheme, setTime 연결
- [x] 닫기 버튼 / 컴포넌트 
- [ ] 장소 검색기능 구현
- [x] 경우에 따른 버튼 변경 => 추가하기(plan 추가) / 신청하기(curation 신청)
### AddPlan일 경우
- [x] planlist(planTimeline?) 빈 공간 클릭 시 추가 창 생성
- [ ] 추가하기 버튼 클릭 시 timeline에 추가
### Curation 요청일 경우
- [x] planpage(왼쪽 상단)에서 + 클릭 시 요청 창 생성
- [x] 신청하기 버튼 클릭 시 API 요청
### PlanPage
- [x] 검색 결과 기존: 주소만 => 변경: 장소명 + 주소

## 못한 것
- AddPlan 내부 검색 기능
- Plan 추가 버튼 클릭 시 => PlanList에 추가
- 검색 시 PlanPage 연동 미구현
