### ISSUE TITLE
[Client] Feature / PlanCard 컴포넌트 구현

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#71]
### Detail
* 레이아웃
* hover 시 x 뜨는거
* Props 잘 생각해서 하기 (테마, 시간 초기값 생각)

### TODO
- [x] 레이아웃 - % 처리
- [x] scss 적용
- [x] setTheme, setTime 겹침현상
  - [x] display 속성, pointer-event 속성 수정
- [x] hover 시 x 버튼 뜨게
- [x] setTheme, setTime - ESC 이벤트 추가

추가해야할 사항
* function형으로 바꾸기
*  setTheme, setTime - 창 안겹치게
