### ISSUE TITLE
[Client] Feature / PlanList - background line, 시간표시 추가

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#76]
### Detail
background line, 시간표시 추가

### TODO
- [x] index값 이용 -> 00:00~24:00 범위 30분 단위로 시간표시 추가
- [x] drag&drop 영역에 background line 추가
- [x] plan관련 scss 수정
