### ISSUE TITLE
[Client] Feature / 마커 영역 캡쳐하기

### ISSUE THREAD

**Issue by Juhye-Kim** [codestates/scraplan-client#95]
### Detail
* 용도 : 카톡 공유 이미지로 쓸 썸네일 사진
* 내일정보기했을 때 상태, 모든 마커 다보이는 상태로 캡쳐

* 카카오맵 정책상 이유로 불가능!

### TODO
- [x] ```html2canvas``` install 및 태그추가
  - [링크](https://html2canvas.hertzen.com/getting-started) 
- [ ] kakao 정적 이미지 생성
- [ ] 정적 이미지를 저장
------
- [ ] 저장버튼 클릭시 
  - [ ] 일정 전 영역 다보이는 상태로 만들기
  - [ ] 캡쳐
  - [ ] 업로드
- [ ] plan저장시 -> planId로 s3에 저장
  - [ ] 수정시에는 -> unpdate
    * 알아서 덮어씌워지는지 확인해보기
